services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - universal-network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'

networks:
  universal-network:
    external: true
