services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /mnt/data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pranav
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mongo_network:

